twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  globals:
    menu_elements: '@App\Service\HamburgerMenu'
    user_config: '@App\Service\UserConfig'
    roles_list: ['ROLE_USER','ROLE_ADMIN']
