debug:
    # Forwards VarDumper Data clones to a centralized server allowing to inspect dumps on CLI or in your browser.
    # See the "server:dump" command to start a new server.
    #dump_destination: "tcp://%env(VAR_DUMPER_SERVER)%"
    dump_destination: "tcp://192.168.1.106:8001"
